### ISSUE TITLE
Update the uuid package

### ISSUE THREAD

**Issue by namnm** [dmarcelino/uuid-base62#5]
The `node-uuid` package is deprecated, should be replaced with `uuid` package instead.

**Comment by shanehughes3** [comment]
It looks like #4 would take care of this, though at this point it's outdated.

It's probably a good idea to lock down those package versions, too.

**Comment by shanehughes3** [comment]
Since this package hasn't been touched in 2 years, I published a fork with updated dependencies: `uuid62`.

**Comment by namnm** [comment]
@shanehughes3 Since the new uuid package has supported for browser, I think your fork should too. Consider to add Buffer https://github.com/feross/buffer as a dependency

**Comment by shanehughes3** [comment]
Good point - I'll add that sometime in the next few days. 

Feel free to open issues on that repo if you notice anything else.

**Comment by namnm** [comment]
@shanehughes3 Thank you, but seems like your fork doesn't allow opening issues. May be you need to change some settings?

**Comment by shanehughes3** [comment]
@namnm whoops, you're right, I forgot that forks have issues disabled by default. Should be enabled now.
